// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpvzavwgefgrizzddnzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwdnphdndnZWZncml6emRkbnp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3Nzk1NDAsImV4cCI6MjA3NDM1NTU0MH0.Cx5yZfqVawZ10ubKKCsHeSxu42DD7MxzMyWuxYXo75g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});